### ISSUE TITLE
removeHorizontalScrollBars is not a function

### ISSUE THREAD

**Issue by uzarsalan** [TheOriginalJosh/nativescript-swiss-army-knife#10]
Hi! I tried remove horizontal ScrollBars, but my app breaks with "removeHorizontalScrollBars is not a function". Plugin is already installed and required to my js file.

**Comment by bradmartin** [comment]
Please see the demo for a sample that is working. https://github.com/TheOriginalJosh/nativescript-swiss-army-knife/blob/master/demo/app/main-view-model.ts#L36
