### ISSUE TITLE
In one project I use it to remove the scrollbar ,but in different page one is effective while one is wrong

### ISSUE THREAD

**Issue by keepCreate** [TheOriginalJosh/nativescript-swiss-army-knife#12]
It is the error:
JS: TypeError: Cannot read property 'setVerticalScrollBarEnabled' of undefined
I don't know why

**Comment by bradmartin** [comment]
Can you provide all relevant code to reproduce this?

**Comment by keepCreate** [comment]
I just use it in onInit() before, and now I find it's wrong, just use it in the ScrollView onloaded() will be fine

**Comment by bradmartin** [comment]
Sounds like a timing issue 🤔

**Comment by keepCreate** [comment]
Yes,if I use it in init(),may be the scrollview not load well
