### ISSUE TITLE
Error using plugin in nativescript android app

### ISSUE THREAD

**Issue by anuragd7** [TheOriginalJosh/nativescript-swiss-army-knife#14]
I installed the plugin using tns plugin add
In the component ts file my code reads

` import { Component, OnInit } from "@angular/core";

    import { Item } from "./item";
    import { ItemService } from "./item.service";
    import { device } from "platform";
    import { DeviceType } from "ui/enums";
    import { ScrollView, ScrollEventData } from "ui/scroll-view";
    import { topmost } from "ui/frame";
    import { SwissArmyKnife } from 'nativescript-swiss-army-knife';

    const isTablet: boolean = (device.deviceType == DeviceType.Tablet);

    @Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
    styleUrls: ['/app/app.css', (isTablet ? '../tablet.css' : '../phone.css')],
    })
    export class ItemsComponent implements OnInit {
    items: Item[];
    constructor(private itemService: ItemService) { }

    ngOnInit(): void {
        this.items = this.itemService.getItems();
        const scrollV = topmost().getViewById("tagView") as ScrollView;
        SwissArmyKnife.removeHorizontalScrollBars(scrollV);
    }
} `

When i run the project I get the following error

`    
    JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'android' of undefined
JS: TypeError: Cannot read property 'android' of undefined
JS:     at Function.SwissArmyKnife.removeHorizontalScrollBars (file:///data/data/org.nativescript.hellong/files/app/tns_modules/nativescript-swiss-army-knife/nativescript-swiss-army-knife.js:44:17)
JS:     at ItemsComponent.ngOnInit (file:///data/data/org.nativescript.hellong/files/app/item/items.component.js:20:56)
JS:     at checkAndUpdateDirectiveInline (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:10822:19)
JS:     at checkAndUpdateNodeInline (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:12245:17)
JS:     at checkAndUpdateNode (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:12184:16)
JS:     at debugCheckAndUpdateNode (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:12887:59)
JS:     at debugCheckDirectivesFn (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:12828:13)
JS:     at Object.eval [as updateDirectives] (ng:///AppModule/ItemsComponent_Host.ngfactory.js:10:5)
JS:     at Object.debugUpdateDirectives [as updateDirectives] (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:12813:21)
JS:     at checkAndUpdateView (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:12151:14)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:13213:42)
JS:     at Object.debugCheckAndUpdateView [as checkAndUpdateView] (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:12753:12)
JS:     at ViewRef_.detectChanges (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:10225:63)
JS:     at PageRouterOutlet.activateOnGoForward (file:///data/data/org.nativescript.hellong/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:155:57)
JS:     at PageRouterOutlet.activateWith (file:///data/data/org.nativescript.hellong/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:140:18)
`

**Comment by bradmartin** [comment]
Try `ngAfterViewInit` it's possible you don't actually have the View
component at the time `ngOnInit` is executed in the ng life cycle.

**Comment by anuragd7** [comment]
Hi 
Thanks for the suggestion. Tried 'ngAfterViewInit'.  Seem to be getting the same error. (see below).

`   JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'android' of undefined
JS: TypeError: Cannot read property 'android' of undefined
JS:     at Function.SwissArmyKnife.removeHorizontalScrollBars (file:///data/data/org.nativescript.hellong/files/app/tns_modules/nativescript-swiss-army-knife/nativescript-swiss-army-knife.js:44:17)
JS:     at ItemsComponent.ngAfterViewInit (file:///data/data/org.nativescript.hellong/files/app/item/items.component.js:20:56)
JS:     at callProviderLifecycles (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:11168:18)
JS:     at callElementProvidersLifecycles (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:11143:13)
JS:     at callLifecycleHooksChildrenFirst (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:11127:17)
JS:     at checkAndUpdateView (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:12159:5)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:13213:42)
JS:     at Object.debugCheckAndUpdateView [as checkAndUpdateView] (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:12753:12)
JS:     at ViewRef_.detectChanges (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:10225:63)
JS:     at PageRouterOutlet.activateOnGoForward (file:///data/data/org.nativescript.hellong/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:155:57)
JS:     at PageRouterOutlet.activateWith (file:///data/data/org.nativescript.hellong/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:140:18)
JS:     at ActivateRoutes.placeComponentIntoOutlet (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/router/bundles/router.umd.js:4526:16)
JS:     at ActivateRoutes.activateRoutes (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/router/bundles/router.umd.js:4507:26)
JS:     at file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/router/bundles/router.umd.js:4443:58
JS:     at Array.forEach (native)
9:09:08 PM - Compilation complete. Watching for file changes. `

**Comment by bradmartin** [comment]
Since `scrollV` is undefined, what does your template look like? Are you using angular id syntax?

**Comment by anuragd7** [comment]
I am using the tagview id in the the html template. 
Have created a [repo ](https://github.com/anuragd7/SwissKnifeIssue)where you can observe the issue I am facing. 
You can look at my angular template [here](https://github.com/anuragd7/SwissKnifeIssue/blob/master/app/item/items.component.html).

Please let me know if I am making some error.

**Comment by bradmartin** [comment]
Thanks. you'll need to use the angular id syntax. Its a little different
declaring an id with Angular. Use `#`

**Comment by anuragd7** [comment]
Many Thanks for the prompt responses.  I made the following changes 
1. declared a [template reference variable](https://angular.io/guide/template-syntax#template-reference-variables--var-)  using #tagView  like so
`    <ScrollView #tagView orientation="horizontal">`
2. Imported viewChild in the ts file and used it to refer to the tagView inside the component file as mentioned [here](https://stackoverflow.com/questions/39631594/angular-2-is-it-possible-to-access-template-reference-variables-from-the-compo) 
`   import { Component, AfterViewInit, ViewChild, ElementRef } from "@angular/core";
 `
`    @ViewChild('tagView') input: ScrollView; 

     ngAfterViewInit(): void {
        this.items = this.itemService.getItems();
        this.removeBar();
     }

    addAnimation() {
        console.log("clicked");
        this.animateButton = !this.animateButton
    }

    removeBar() {
        const scrollV = this.input;
        SwissArmyKnife.removeHorizontalScrollBars(scrollV);
    }`

Now I am getting an error 

`JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'setHorizontalScrollBarEnabled' of undefined
JS: TypeError: Cannot read property 'setHorizontalScrollBarEnabled' of undefined
JS:     at Function.SwissArmyKnife.removeHorizontalScrollBars (file:///data/data/org.nativescript.hellong/files/app/tns_modules/nativescript-swiss-army-knife/nativescript-swiss-army-knife.js:44:25)
JS:     at ItemsComponent.removeBar (file:///data/data/org.nativescript.hellong/files/app/item/items.component.js:27:56)
JS:     at ItemsComponent.ngAfterViewInit (file:///data/data/org.nativescript.hellong/files/app/item/items.component.js:19:14)
JS:     at callProviderLifecycles (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:11168:18)
JS:     at callElementProvidersLifecycles (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:11143:13)
JS:     at callLifecycleHooksChildrenFirst (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:11127:17)
JS:     at checkAndUpdateView (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:12159:5)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:13213:42)
JS:     at Object.debugCheckAndUpdateView [as checkAndUpdateView] (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:12753:12)
JS:     at ViewRef_.detectChanges (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/core/bundles/core.umd.js:10225:63)
JS:     at PageRouterOutlet.activateOnGoForward (file:///data/data/org.nativescript.hellong/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:155:57)
JS:     at PageRouterOutlet.activateWith (file:///data/data/org.nativescript.hellong/files/app/tns_modules/nativescript-angular/router/page-router-outlet.js:140:18)
JS:     at ActivateRoutes.placeComponentIntoOutlet (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/router/bundles/router.umd.js:4526:16)
JS:     at ActivateRoutes.activateRoutes (file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/router/bundles/router.umd.js:4507:26)
JS:     at file:///data/data/org.nativescript.hellong/files/app/tns_modules/@angular/router/bundles/router.umd.js:4443:58
12:38:45 PM - Compilation complete. Watching for file changes.`

**Comment by bradmartin** [comment]
See this
http://www.nativescriptsnacks.com/snippets/2016/07/07/redo-basic-app-in-ng2.html
you're close. If this doesn't help you should try debugging and see what
that view element is. This should help you figure it out :)

**Comment by anuragd7** [comment]
Thanks for the link. it was helpful. I used ViewChild as shown in the component file (shown below) and also debugged the code. It seems that SwissArmyKnife is undefined,  even though I installed the plugin and am importing it  in the component like so
`   import { SwissArmyKnife } from 'nativescript-swiss-army-knife'; `

On tns run android I get the error 
`     TypeError: Cannot read property 'setHorizontalScrollBarEnabled' of undefined
JS:     at Function.SwissArmyKnife.removeHorizontalScrollBars (file:///data/data/org.nativescript.hellong/files/app/tns_modules/nativescript-swiss-army-knife/nativescript-swiss-army-knife.js:44:25)`

My component code is
 ```
export class ItemsComponent implements AfterViewInit {
    @ViewChild('tagView') input: ElementRef;

```
```
ngAfterViewInit(): void {
        this.items = this.itemService.getItems();
        const scrollV = this.input.nativeElement;
        SwissArmyKnife.removeHorizontalScrollBars(scrollV);
    } 
```

**Comment by Taremeh** [comment]
Still getting similar errors... Is there a working example of removing ScrollBars from ScrollViews, based on Nativescript Angular2 + Typescript?

**Comment by cfoulkes** [comment]
I also have the same issue.

Putting the calls in a setTimeout works, but I'm never comfortable using this approach. Is there another solution?

ngAfterViewInit(): void {
        const scrollV = this.scrollView.nativeElement;
       setTimeout(function() {
           SwissArmyKnife.removeHorizontalScrollBars(scrollV);
        }, 10);
    } 


Thanks
Colin

**Comment by JoshDSommer** [comment]
With NativeScript + Angular, it's best to use the `(loaded)` event on the components themselves to apply these updates.
