### ISSUE TITLE
New release for https://github.com/TheOriginalJosh/nativescript-swiss-army-knife/pull/16

### ISSUE THREAD

**Issue by gummibjorn** [TheOriginalJosh/nativescript-swiss-army-knife#17]
Hi, I would be very thankful for a new release including https://github.com/TheOriginalJosh/nativescript-swiss-army-knife/pull/16.

Thanks!

**Comment by JoshDSommer** [comment]
@gummibjorn I attempted to release this the other day but was having some problems getting the projects working, it had been a while since I had worked on it. will attempt again later today. sorry for the delay.

**Comment by bradmartin** [comment]
@TheOriginalJosh I can publish this later if you can check npm and give me access on the package.

**Comment by JoshDSommer** [comment]
@bradmartin Sweet! you should already have access, it says you did the last release 💃

**Comment by bradmartin** [comment]
3.1.0 published
