### ISSUE TITLE
Feature Request: connectivity status

### ISSUE THREAD

**Issue by jaasaria** [TheOriginalJosh/nativescript-swiss-army-knife#20]
hello, first thank you for this wonderfull plugin. 
If its okay i would like to request a feature to add on this plugin, internet connectivity status. :)
i think it will be more awesome if utility feature like my request will be added on this plugin.
more power and thank you in advance.

**Comment by JoshDSommer** [comment]
@jaasaria Thank you! The NativeScript framework already has some good utilities for connectivity, not sure if these are what you were looking for is there something else missing? https://docs.nativescript.org/ns-framework-modules/connectivity

**Comment by JoshDSommer** [comment]
Going to close this for the time being, if you feel free to re-open if you find the NativeScript utilities don’t suffice.
